repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: check-toml
    -   id: check-json
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.289
    hooks:
    -   id: ruff
        name: ruff-format
        args: [--format-only, --exit-non-zero-on-fix]
        types: [python]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies: ["pydantic>=2.0.0"]
        args: [--strict]
        exclude: ^tests/
        types: [python]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-log-warn
    -   id: python-use-type-annotations

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
    -   id: prettier
        types: [yaml, json, markdown, html, css, javascript]

ci:
  autofix_commit_msg: "style: auto-fix by pre-commit hooks"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: true
  autoupdate_schedule: monthly
