# config.yaml - User Configuration (Overrides defaults in config.py)

output:
  directory: output  # Relative to project root
  scraped_jobs_file: scraped_jobs.parquet
  analysis_output_file: analysis_results.json
  debug_output_file: debug_info.json

ollama:
  base_url: http://localhost:11434
  #model: deepseek-r1:14b  # Example - adjust as needed
  model: llama3:instruct  # Example - adjust as needed
  request_timeout: 900    # Timeout in seconds
  max_retries: 2
  retry_delay: 5

analysis:
  prompts_dir: analysis/prompts
  resume_prompt_file: resume_extraction.prompt
  suitability_prompt_file: suitability_analysis.prompt
  job_extraction_prompt_file: job_extraction.prompt
  max_prompt_chars: 24000

scraping:
  default_sites: ["linkedin"]
  default_results_limit: 50
  default_days_old: 3  # Use days, not hours
  default_country_indeed: "usa"
  linkedin_fetch_description: true
  linkedin_company_ids: []

geocoding:
  geopy_user_agent: "MyJobSpyAI/1.0 (your_email@example.com)" # Update with your email

logging:
  level: INFO
  format: "%(message)s"
  date_format: "[%X]"