site_name: MyJobSpyAI
docs_dir: .
site_description: 'Documentation for MyJobSpyAI'
site_author: 'Your Name'
theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.fuzzy
    - search.shortcut
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.code.hilite
    - content.tabs.link
    - content.tabs.sticky
    - content.tooltips
    - content.code.line-numbers
    - content.code.wrap
    - content.code.highlight
    - content.code.scroll
  palette:
    primary: "blue"
    accent: "blue"
    scheme: auto
    toggle:
      icon: material/toggle-switch
      name: Switch color scheme
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    home: material/home
    menu: material/menu
    toc: material/toc
    search: material/magnify
    prev: material/chevron-left
    next: material/chevron-right
    tools: material/tools

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
      pygments_style: monokai
      linenums: true
      anchor_linenums: true
      line_spans: __line_
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences
  - toc:
      permalink: true
      separator: '-'
  - pymdownx.details

plugins:
  - search
  - macros
  - autolinks
  - minify
  - awesome-pages
  - redirects

extra:
  mermaid:
    startOnLoad: true
    theme: 'default'
    cloneCssStyles: false
    securityLevel: 'loose'
    logLevel: 'info'
    flowchart:
      htmlLabels: true
      useMaxWidth: false
    sequence:
      diagramTop: 'Requirement'
      actorMargin: 50
      width: 150
      height: 65
      boxMargin: 10
      boxTextMargin: 5
      noteMargin: 10
    gantt:
      titleTopMargin: 25
      barHeight: 20
      barGap: 4
      topPadding: 50
      leftPadding: 75
      gridLineStartPadding: 35
      fontSize: 11
      numberSectionStyles: 4
      axisFormatter: 'DD MMM YYYY'

nav:
  - Home: index.md
  - Getting Started:
    - Introduction: getting_started/introduction.md
  - Features:
    - Job Analysis: features/job_analysis.md
    - Job Scraping: features/job_scraping.md
    - Resume Matching: features/resume_matching.md
    - Example Features: features/example_features.md
  - Development:
    - Code Style: development/code_style.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md
    - Contributing: development/contributing.md
  - Enhancement Plans:
    - Overview: enhancement_plans/roadmap.md
    - Future Features: enhancement_plans/future_features.md
    - Resume Job Suitability: enhancement_plans/2024-06-05_resume_job_suitability_enhancement.md
  - API Reference:
    - Overview: api/reference.md
    - Main: api/myjobspyai.md
    - Analysis: api/myjobspyai.analysis.md
    - Analysis Providers: api/myjobspyai.analysis.providers.md
    - Analysis Providers Base: api/myjobspyai.analysis.providers.base.md
    - Analysis Providers Factory: api/myjobspyai.analysis.providers.factory.md
    - Analysis Providers LangChain: api/myjobspyai.analysis.providers.langchain_provider.md
    - Analysis Utils: api/myjobspyai.analysis.utils.md
    - Analysis Chunking: api/myjobspyai.analysis.chunking_utils.md
    - Analysis Chunking Utils: api/myjobspyai.analysis.utils.chunking.md
    - Analysis LangChain OTel: api/myjobspyai.analysis.utils.langchain_otel.md
    - Analysis Models: api/myjobspyai.analysis.models.md
    - Analysis Analyzer: api/myjobspyai.analysis.analyzer.md
    - Config: api/myjobspyai.config.md
    - LLM: api/myjobspyai.llm.md
    - LLM LangChain: api/myjobspyai.llm.providers.langchain.md
    - LLM Ollama: api/myjobspyai.llm.providers.ollama.md
    - Main Matcher: api/myjobspyai.main_matcher.md
    - Main: api/myjobspyai.main.md
    - Parsers: api/myjobspyai.parsers.md
    - Job Parser: api/myjobspyai.parsers.job_parser.md
    - Resume Parser: api/myjobspyai.parsers.resume_parser.md
    - Prompts: api/myjobspyai.prompts.md
    - API Index: api/index.md
    - API Modules: api/modules.md
  - Support:
    - Troubleshooting: support/troubleshooting.md
    - Changelog: changelog.md
    - Filtering:
      - Overview: api/myjobspyai.filtering.md
      - Filter: api/myjobspyai.filtering.filter.md
      - Filter Utils: api/myjobspyai.filtering.filter_utils.md
    - LLM:
      - Overview: api/myjobspyai.llm.md
      - Base: api/myjobspyai.llm.base.md
      - Providers: api/myjobspyai.llm.providers.md
    - Scrapers:
      - Overview: api/myjobspyai.scrapers.md
      - Base: api/myjobspyai.scrapers.base.md
      - Factory: api/myjobspyai.scrapers.factory.md
      - JobSpy: api/myjobspyai.scrapers.jobspy_scraper.md
      - LinkedIn: api/myjobspyai.scrapers.linkedin.md
      - Indeed: api/myjobspyai.scrapers.indeed.md
    - Models:
      - Overview: api/myjobspyai.models.md
      - Job: api/myjobspyai.models.job.md
      - Resume: api/myjobspyai.models.resume.md
      - Analysis: api/myjobspyai.models.analysis.md
    - Utils:
      - Overview: api/myjobspyai.utils.md
      - Async Utils: api/myjobspyai.utils.async_utils.md
      - Env: api/myjobspyai.utils.env.md
      - Files: api/myjobspyai.utils.files.md
      - HTTP Client: api/myjobspyai.utils.http_client.md
      - Logging: api/myjobspyai.utils.logging.md
      - Logging Utils: api/myjobspyai.utils.logging_utils.md
      - Prompts: api/myjobspyai.utils.prompts.md
      - Validation: api/myjobspyai.utils.validation.md
  - Development:
    - Contributing: development/contributing.md
    - Code Style: development/code_style.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md
    - icon: fontawesome/brands/github
      link: https://github.com/kasnycdev/MyJobSpyAI

edit_uri: edit/master/docs/
repo_url: https://github.com/kasnycdev/MyJobSpyAI
repo_name: GitHub
